<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\runtimes\dotnet\DynamicLinkLibraries\AssemblyService\AssemblyService.csproj" />
    <ProjectReference Include="..\..\..\..\..\runtimes\dotnet\DynamicLinkLibraries\Diagram\Diagram\Diagram.csproj" />
  </ItemGroup>

</Project>
