"use strict";
/* eslint-disable @typescript-eslint/no-unused-vars */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AntiAliasingKernel = exports.AbstractKernel = exports.NdcFillingTriangle = exports.NdcFillingRectangle = exports.CanvasRecorder = exports.WheelZoomModifier = exports.PinchZoomModifier = exports.TurntableModifier = exports.TrackballModifier = exports.PointerLock = exports.PanModifier = exports.FirstPersonModifier = exports.Navigation = exports.CameraModifier = exports.TileCameraGenerator = exports.Camera = exports.Wizard = exports.VertexArray = exports.UnifiedBuffer = exports.TextureCube = exports.Texture2DArray = exports.Texture3D = exports.Texture2D = exports.Shader = exports.LoadingStatus = exports.Invalidate = exports.Renderer = exports.Renderbuffer = exports.Program = exports.Geometry = exports.Framebuffer = exports.DefaultFramebuffer = exports.ColorScale = exports.Color = exports.Buffer = exports.EventProvider = exports.EventHandler = exports.PointerEventProvider = exports.TouchEventProvider = exports.MouseEventProvider = exports.ChangeLookup = exports.ExtensionsHash = exports.ContextMasquerade = exports.Initializable = exports.Controller = exports.Canvas = exports.Context = exports.version = exports.commit = exports.branch = void 0;
exports.tuples = exports.gl_matrix_extensions = exports.quat = exports.mat4 = exports.mat3 = exports.mat2d = exports.mat2 = exports.vec4 = exports.vec3 = exports.vec2 = exports.auxiliaries = exports.FrameCapture = exports.EyeGazeData = exports.EyeGazeEvent = exports.EyeGazeEventProvider = exports.EyeGazeDataStreams = exports.EyeGazeDataStream = exports.ShadowPass = exports.GaussFilter = exports.ReadbackPass = exports.EnvironmentTextureType = exports.EnvironmentRenderingPass = exports.DebugPass = exports.BlitPass = exports.AccumulatePass = exports.KernelUI8 = exports.KernelUI32 = exports.KernelI8 = exports.KernelI32 = exports.KernelF32 = exports.RandomSquareKernel = void 0;
/* spellchecker: disable */
var version_1 = require("./version");
Object.defineProperty(exports, "branch", { enumerable: true, get: function () { return version_1.branch; } });
Object.defineProperty(exports, "commit", { enumerable: true, get: function () { return version_1.commit; } });
Object.defineProperty(exports, "version", { enumerable: true, get: function () { return version_1.version; } });
var context_1 = require("./context");
Object.defineProperty(exports, "Context", { enumerable: true, get: function () { return context_1.Context; } });
var canvas_1 = require("./canvas");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return canvas_1.Canvas; } });
var controller_1 = require("./controller");
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_1.Controller; } });
var initializable_1 = require("./initializable");
Object.defineProperty(exports, "Initializable", { enumerable: true, get: function () { return initializable_1.Initializable; } });
var contextmasquerade_1 = require("./contextmasquerade");
Object.defineProperty(exports, "ContextMasquerade", { enumerable: true, get: function () { return contextmasquerade_1.ContextMasquerade; } });
var extensionshash_1 = require("./extensionshash");
Object.defineProperty(exports, "ExtensionsHash", { enumerable: true, get: function () { return extensionshash_1.ExtensionsHash; } });
var changelookup_1 = require("./changelookup");
Object.defineProperty(exports, "ChangeLookup", { enumerable: true, get: function () { return changelookup_1.ChangeLookup; } });
var mouseeventprovider_1 = require("./mouseeventprovider");
Object.defineProperty(exports, "MouseEventProvider", { enumerable: true, get: function () { return mouseeventprovider_1.MouseEventProvider; } });
var toucheventprovider_1 = require("./toucheventprovider");
Object.defineProperty(exports, "TouchEventProvider", { enumerable: true, get: function () { return toucheventprovider_1.TouchEventProvider; } });
var pointereventprovider_1 = require("./pointereventprovider");
Object.defineProperty(exports, "PointerEventProvider", { enumerable: true, get: function () { return pointereventprovider_1.PointerEventProvider; } });
var eventhandler_1 = require("./eventhandler");
Object.defineProperty(exports, "EventHandler", { enumerable: true, get: function () { return eventhandler_1.EventHandler; } });
Object.defineProperty(exports, "EventProvider", { enumerable: true, get: function () { return eventhandler_1.EventProvider; } });
var buffer_1 = require("./buffer");
Object.defineProperty(exports, "Buffer", { enumerable: true, get: function () { return buffer_1.Buffer; } });
var color_1 = require("./color");
Object.defineProperty(exports, "Color", { enumerable: true, get: function () { return color_1.Color; } });
var colorscale_1 = require("./colorscale");
Object.defineProperty(exports, "ColorScale", { enumerable: true, get: function () { return colorscale_1.ColorScale; } });
var defaultframebuffer_1 = require("./defaultframebuffer");
Object.defineProperty(exports, "DefaultFramebuffer", { enumerable: true, get: function () { return defaultframebuffer_1.DefaultFramebuffer; } });
var framebuffer_1 = require("./framebuffer");
Object.defineProperty(exports, "Framebuffer", { enumerable: true, get: function () { return framebuffer_1.Framebuffer; } });
var geometry_1 = require("./geometry");
Object.defineProperty(exports, "Geometry", { enumerable: true, get: function () { return geometry_1.Geometry; } });
var program_1 = require("./program");
Object.defineProperty(exports, "Program", { enumerable: true, get: function () { return program_1.Program; } });
var renderbuffer_1 = require("./renderbuffer");
Object.defineProperty(exports, "Renderbuffer", { enumerable: true, get: function () { return renderbuffer_1.Renderbuffer; } });
var renderer_1 = require("./renderer");
Object.defineProperty(exports, "Renderer", { enumerable: true, get: function () { return renderer_1.Renderer; } });
Object.defineProperty(exports, "Invalidate", { enumerable: true, get: function () { return renderer_1.Invalidate; } });
Object.defineProperty(exports, "LoadingStatus", { enumerable: true, get: function () { return renderer_1.LoadingStatus; } });
var shader_1 = require("./shader");
Object.defineProperty(exports, "Shader", { enumerable: true, get: function () { return shader_1.Shader; } });
var texture2d_1 = require("./texture2d");
Object.defineProperty(exports, "Texture2D", { enumerable: true, get: function () { return texture2d_1.Texture2D; } });
var texture3d_1 = require("./texture3d");
Object.defineProperty(exports, "Texture3D", { enumerable: true, get: function () { return texture3d_1.Texture3D; } });
var texture2darray_1 = require("./texture2darray");
Object.defineProperty(exports, "Texture2DArray", { enumerable: true, get: function () { return texture2darray_1.Texture2DArray; } });
var texturecube_1 = require("./texturecube");
Object.defineProperty(exports, "TextureCube", { enumerable: true, get: function () { return texturecube_1.TextureCube; } });
var unifiedbuffer_1 = require("./unifiedbuffer");
Object.defineProperty(exports, "UnifiedBuffer", { enumerable: true, get: function () { return unifiedbuffer_1.UnifiedBuffer; } });
var vertexarray_1 = require("./vertexarray");
Object.defineProperty(exports, "VertexArray", { enumerable: true, get: function () { return vertexarray_1.VertexArray; } });
var wizard_1 = require("./wizard");
Object.defineProperty(exports, "Wizard", { enumerable: true, get: function () { return wizard_1.Wizard; } });
var camera_1 = require("./camera");
Object.defineProperty(exports, "Camera", { enumerable: true, get: function () { return camera_1.Camera; } });
var tilecameragenerator_1 = require("./tilecameragenerator");
Object.defineProperty(exports, "TileCameraGenerator", { enumerable: true, get: function () { return tilecameragenerator_1.TileCameraGenerator; } });
var cameramodifier_1 = require("./cameramodifier");
Object.defineProperty(exports, "CameraModifier", { enumerable: true, get: function () { return cameramodifier_1.CameraModifier; } });
var navigation_1 = require("./navigation");
Object.defineProperty(exports, "Navigation", { enumerable: true, get: function () { return navigation_1.Navigation; } });
var firstpersonmodifier_1 = require("./firstpersonmodifier");
Object.defineProperty(exports, "FirstPersonModifier", { enumerable: true, get: function () { return firstpersonmodifier_1.FirstPersonModifier; } });
var panmodifier_1 = require("./panmodifier");
Object.defineProperty(exports, "PanModifier", { enumerable: true, get: function () { return panmodifier_1.PanModifier; } });
var pointerlock_1 = require("./pointerlock");
Object.defineProperty(exports, "PointerLock", { enumerable: true, get: function () { return pointerlock_1.PointerLock; } });
var trackballmodifier_1 = require("./trackballmodifier");
Object.defineProperty(exports, "TrackballModifier", { enumerable: true, get: function () { return trackballmodifier_1.TrackballModifier; } });
var turntablemodifier_1 = require("./turntablemodifier");
Object.defineProperty(exports, "TurntableModifier", { enumerable: true, get: function () { return turntablemodifier_1.TurntableModifier; } });
var pinchzoommodifier_1 = require("./pinchzoommodifier");
Object.defineProperty(exports, "PinchZoomModifier", { enumerable: true, get: function () { return pinchzoommodifier_1.PinchZoomModifier; } });
var wheelzoommodifier_1 = require("./wheelzoommodifier");
Object.defineProperty(exports, "WheelZoomModifier", { enumerable: true, get: function () { return wheelzoommodifier_1.WheelZoomModifier; } });
var canvasrecorder_1 = require("./canvasrecorder");
Object.defineProperty(exports, "CanvasRecorder", { enumerable: true, get: function () { return canvasrecorder_1.CanvasRecorder; } });
var ndcfillingrectangle_1 = require("./ndcfillingrectangle");
Object.defineProperty(exports, "NdcFillingRectangle", { enumerable: true, get: function () { return ndcfillingrectangle_1.NdcFillingRectangle; } });
var ndcfillingtriangle_1 = require("./ndcfillingtriangle");
Object.defineProperty(exports, "NdcFillingTriangle", { enumerable: true, get: function () { return ndcfillingtriangle_1.NdcFillingTriangle; } });
var kernel_1 = require("./kernel");
Object.defineProperty(exports, "AbstractKernel", { enumerable: true, get: function () { return kernel_1.AbstractKernel; } });
var antialiasingkernel_1 = require("./antialiasingkernel");
Object.defineProperty(exports, "AntiAliasingKernel", { enumerable: true, get: function () { return antialiasingkernel_1.AntiAliasingKernel; } });
var randomsquarekernel_1 = require("./randomsquarekernel");
Object.defineProperty(exports, "RandomSquareKernel", { enumerable: true, get: function () { return randomsquarekernel_1.RandomSquareKernel; } });
var kernel_2 = require("./kernel");
Object.defineProperty(exports, "KernelF32", { enumerable: true, get: function () { return kernel_2.KernelF32; } });
Object.defineProperty(exports, "KernelI32", { enumerable: true, get: function () { return kernel_2.KernelI32; } });
Object.defineProperty(exports, "KernelI8", { enumerable: true, get: function () { return kernel_2.KernelI8; } });
Object.defineProperty(exports, "KernelUI32", { enumerable: true, get: function () { return kernel_2.KernelUI32; } });
Object.defineProperty(exports, "KernelUI8", { enumerable: true, get: function () { return kernel_2.KernelUI8; } });
var accumulatepass_1 = require("./accumulatepass");
Object.defineProperty(exports, "AccumulatePass", { enumerable: true, get: function () { return accumulatepass_1.AccumulatePass; } });
var blitpass_1 = require("./blitpass");
Object.defineProperty(exports, "BlitPass", { enumerable: true, get: function () { return blitpass_1.BlitPass; } });
var debugpass_1 = require("./debugpass");
Object.defineProperty(exports, "DebugPass", { enumerable: true, get: function () { return debugpass_1.DebugPass; } });
var environmentrenderingpass_1 = require("./environmentrenderingpass");
Object.defineProperty(exports, "EnvironmentRenderingPass", { enumerable: true, get: function () { return environmentrenderingpass_1.EnvironmentRenderingPass; } });
Object.defineProperty(exports, "EnvironmentTextureType", { enumerable: true, get: function () { return environmentrenderingpass_1.EnvironmentTextureType; } });
var readbackpass_1 = require("./readbackpass");
Object.defineProperty(exports, "ReadbackPass", { enumerable: true, get: function () { return readbackpass_1.ReadbackPass; } });
var gaussfilter_1 = require("./gaussfilter");
Object.defineProperty(exports, "GaussFilter", { enumerable: true, get: function () { return gaussfilter_1.GaussFilter; } });
var shadowpass_1 = require("./shadowpass");
Object.defineProperty(exports, "ShadowPass", { enumerable: true, get: function () { return shadowpass_1.ShadowPass; } });
var eyegazedatastream_1 = require("./eyegazedatastream");
Object.defineProperty(exports, "EyeGazeDataStream", { enumerable: true, get: function () { return eyegazedatastream_1.EyeGazeDataStream; } });
Object.defineProperty(exports, "EyeGazeDataStreams", { enumerable: true, get: function () { return eyegazedatastream_1.EyeGazeDataStreams; } });
var eyegazeeventprovider_1 = require("./eyegazeeventprovider");
Object.defineProperty(exports, "EyeGazeEventProvider", { enumerable: true, get: function () { return eyegazeeventprovider_1.EyeGazeEventProvider; } });
var eyegazeevent_1 = require("./eyegazeevent");
Object.defineProperty(exports, "EyeGazeEvent", { enumerable: true, get: function () { return eyegazeevent_1.EyeGazeEvent; } });
Object.defineProperty(exports, "EyeGazeData", { enumerable: true, get: function () { return eyegazeevent_1.EyeGazeData; } });
var framecapture_1 = require("./framecapture");
Object.defineProperty(exports, "FrameCapture", { enumerable: true, get: function () { return framecapture_1.FrameCapture; } });
__exportStar(require("./core/index"), exports);
__exportStar(require("./scene/index"), exports);
__exportStar(require("./text/index"), exports);
/* AUXILIARIES */
const root_auxiliaries = __importStar(require("./auxiliaries"));
exports.auxiliaries = root_auxiliaries;
var gl_matrix_1 = require("gl-matrix");
Object.defineProperty(exports, "vec2", { enumerable: true, get: function () { return gl_matrix_1.vec2; } });
Object.defineProperty(exports, "vec3", { enumerable: true, get: function () { return gl_matrix_1.vec3; } });
Object.defineProperty(exports, "vec4", { enumerable: true, get: function () { return gl_matrix_1.vec4; } });
var gl_matrix_2 = require("gl-matrix");
Object.defineProperty(exports, "mat2", { enumerable: true, get: function () { return gl_matrix_2.mat2; } });
Object.defineProperty(exports, "mat2d", { enumerable: true, get: function () { return gl_matrix_2.mat2d; } });
Object.defineProperty(exports, "mat3", { enumerable: true, get: function () { return gl_matrix_2.mat3; } });
Object.defineProperty(exports, "mat4", { enumerable: true, get: function () { return gl_matrix_2.mat4; } });
var gl_matrix_3 = require("gl-matrix");
Object.defineProperty(exports, "quat", { enumerable: true, get: function () { return gl_matrix_3.quat; } });
const root_gl_matrix_extensions = __importStar(require("./gl-matrix-extensions"));
exports.gl_matrix_extensions = root_gl_matrix_extensions;
const root_tuples = __importStar(require("./tuples"));
exports.tuples = root_tuples;
/* spellchecker: enable */
//# sourceMappingURL=webgl-operate.slim.js.map