// Licence file C:\Users\monst\OneDrive\Documents\ReversePOCO.txt not found.
// Please obtain your licence file at www.ReversePOCO.co.uk, and place it in your documents folder shown above.
// Defaulting to Trial version.
// <auto-generated>
// ReSharper disable All

using ErrorHandler;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace DataWarehouse.SQLServer.EntityFramework
{
    #region Database context interface

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public interface IDataWarehouse : IDisposable
    {
        DbSet<BinaryTable> BinaryTables { get; set; } // BinaryTable
        DbSet<BinaryTree> BinaryTrees { get; set; } // BinaryTree
        DbSet<ViewBinaryTableId> ViewBinaryTableIds { get; set; } // ViewBinaryTableId
        DbSet<ViewBinaryTableInfo> ViewBinaryTableInfoes { get; set; } // ViewBinaryTableInfo
        DbSet<ViewBinaryTreeId> ViewBinaryTreeIds { get; set; } // ViewBinaryTreeId

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity Find<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken);
        ValueTask<object> FindAsync(Type entityType, params object[] keyValues);
        object Find(Type entityType, params object[] keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);

        // Stored Procedures
        int DeleteBinary(Guid? id);
        Task<int> DeleteBinaryAsync(Guid? id, CancellationToken cancellationToken = default(CancellationToken));

        int DeleteBinaryTree(Guid? id);
        Task<int> DeleteBinaryTreeAsync(Guid? id, CancellationToken cancellationToken = default(CancellationToken));

        int InsertBinary(Guid? parentId, string name, string description, byte[] data, string ext);
        Task<int> InsertBinaryAsync(Guid? parentId, string name, string description, byte[] data, string ext, CancellationToken cancellationToken = default(CancellationToken));

        int InsertBinaryInterface(Guid? parentId, string name, string description, byte[] data, int? length, string ext, string interfaceName);
        Task<int> InsertBinaryInterfaceAsync(Guid? parentId, string name, string description, byte[] data, int? length, string ext, string interfaceName, CancellationToken cancellationToken = default(CancellationToken));

        List<InsertBinaryNodeReturnModel> InsertBinaryNode(Guid? parentId, string name, string description, string ext);
        List<InsertBinaryNodeReturnModel> InsertBinaryNode(Guid? parentId, string name, string description, string ext, out int procResult);
        Task<List<InsertBinaryNodeReturnModel>> InsertBinaryNodeAsync(Guid? parentId, string name, string description, string ext, CancellationToken cancellationToken = default(CancellationToken));

        List<InsertTreeReturnModel> InsertTree(Guid? parentId, string name, string description, string ext);
        List<InsertTreeReturnModel> InsertTree(Guid? parentId, string name, string description, string ext, out int procResult);
        Task<List<InsertTreeReturnModel>> InsertTreeAsync(Guid? parentId, string name, string description, string ext, CancellationToken cancellationToken = default(CancellationToken));

        List<ProcedureReturnModel> Procedure(int? param1, int? param2);
        List<ProcedureReturnModel> Procedure(int? param1, int? param2, out int procResult);
        Task<List<ProcedureReturnModel>> ProcedureAsync(int? param1, int? param2, CancellationToken cancellationToken = default(CancellationToken));

        List<SelectBinaryReturnModel> SelectBinary(Guid? id);
        List<SelectBinaryReturnModel> SelectBinary(Guid? id, out int procResult);
        Task<List<SelectBinaryReturnModel>> SelectBinaryAsync(Guid? id, CancellationToken cancellationToken = default(CancellationToken));

        List<SelectBinaryContentsReturnModel> SelectBinaryContents(string ext);
        List<SelectBinaryContentsReturnModel> SelectBinaryContents(string ext, out int procResult);
        Task<List<SelectBinaryContentsReturnModel>> SelectBinaryContentsAsync(string ext, CancellationToken cancellationToken = default(CancellationToken));

        List<SelectBinaryTableReturnModel> SelectBinaryTable();
        List<SelectBinaryTableReturnModel> SelectBinaryTable(out int procResult);
        Task<List<SelectBinaryTableReturnModel>> SelectBinaryTableAsync(CancellationToken cancellationToken = default(CancellationToken));

    }

    #endregion

    #region Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class DataWarehouse : DbContext, IDataWarehouse
    {
        public DataWarehouse()
        {
        }

        public DataWarehouse(DbContextOptions<DataWarehouse> options)
            : base(options)
        {
        }

        public DbSet<BinaryTable> BinaryTables { get; set; } // BinaryTable
        public DbSet<BinaryTree> BinaryTrees { get; set; } // BinaryTree
        public DbSet<ViewBinaryTableId> ViewBinaryTableIds { get; set; } // ViewBinaryTableId
        public DbSet<ViewBinaryTableInfo> ViewBinaryTableInfoes { get; set; } // ViewBinaryTableInfo
        public DbSet<ViewBinaryTreeId> ViewBinaryTreeIds { get; set; } // ViewBinaryTreeId

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=IVANKOV\SQLEXPRESS;Initial Catalog=Trading_Analytics;Integrated Security=True;MultipleActiveResultSets=True;Encrypt=false;TrustServerCertificate=true");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new BinaryTableConfiguration());
            modelBuilder.ApplyConfiguration(new BinaryTreeConfiguration());
            modelBuilder.ApplyConfiguration(new ViewBinaryTableIdConfiguration());
            modelBuilder.ApplyConfiguration(new ViewBinaryTableInfoConfiguration());
            modelBuilder.ApplyConfiguration(new ViewBinaryTreeIdConfiguration());

            modelBuilder.Entity<InsertBinaryNodeReturnModel>().HasNoKey();
            modelBuilder.Entity<InsertTreeReturnModel>().HasNoKey();
            modelBuilder.Entity<ProcedureReturnModel>().HasNoKey();
            modelBuilder.Entity<SelectBinaryReturnModel>().HasNoKey();
            modelBuilder.Entity<SelectBinaryContentsReturnModel>().HasNoKey();
            modelBuilder.Entity<SelectBinaryTableReturnModel>().HasNoKey();
        }


        // Stored Procedures
        public int DeleteBinary(Guid? id = null)
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[DeleteBinary] @Id", idParam, procResultParam);

            return (int)procResultParam.Value;
        }

        public async Task<int> DeleteBinaryAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            await Database.ExecuteSqlRawAsync("EXEC @procResult = [dbo].[DeleteBinary] @Id",  new[] {idParam, procResultParam}, cancellationToken);

            return (int)procResultParam.Value;
        }

        public int DeleteBinaryTree(Guid? id = null)
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[DeleteBinaryTree] @Id", idParam, procResultParam);

            return (int)procResultParam.Value;
        }

        public async Task<int> DeleteBinaryTreeAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            await Database.ExecuteSqlRawAsync("EXEC @procResult = [dbo].[DeleteBinaryTree] @Id",  new[] {idParam, procResultParam}, cancellationToken);

            return (int)procResultParam.Value;
        }

        public int InsertBinary(Guid? parentId, string name, string description, byte[] data, string ext)
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@Name", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var dataParam = new SqlParameter { ParameterName = "@Data", SqlDbType = SqlDbType.Image, Direction = ParameterDirection.Input, Value = data, Size = 2147483647 };
            if (dataParam.Value == null)
                dataParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[InsertBinary] @ParentId, @Name, @Description, @Data, @Ext", parentIdParam, nameParam, descriptionParam, dataParam, extParam, procResultParam);

            return (int)procResultParam.Value;
        }

        public async Task<int> InsertBinaryAsync(Guid? parentId, string name, string description, byte[] data, string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@Name", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var dataParam = new SqlParameter { ParameterName = "@Data", SqlDbType = SqlDbType.Image, Direction = ParameterDirection.Input, Value = data, Size = 2147483647 };
            if (dataParam.Value == null)
                dataParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            await Database.ExecuteSqlRawAsync("EXEC @procResult = [dbo].[InsertBinary] @ParentId, @Name, @Description, @Data, @Ext",  new[] {parentIdParam, nameParam, descriptionParam, dataParam, extParam, procResultParam}, cancellationToken);

            return (int)procResultParam.Value;
        }

        public int InsertBinaryInterface(Guid? parentId, string name, string description, byte[] data, int? length, string ext, string interfaceName)
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@Name", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var dataParam = new SqlParameter { ParameterName = "@Data", SqlDbType = SqlDbType.Image, Direction = ParameterDirection.Input, Value = data, Size = 2147483647 };
            if (dataParam.Value == null)
                dataParam.Value = DBNull.Value;

            var lengthParam = new SqlParameter { ParameterName = "@Length", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = length.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!length.HasValue)
                lengthParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var interfaceNameParam = new SqlParameter { ParameterName = "@InterfaceName", SqlDbType = SqlDbType.VarChar, Direction = ParameterDirection.Input, Value = interfaceName, Size = 100 };
            if (interfaceNameParam.Value == null)
                interfaceNameParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[InsertBinaryInterface] @ParentId, @Name, @Description, @Data, @Length, @Ext, @InterfaceName", parentIdParam, nameParam, descriptionParam, dataParam, lengthParam, extParam, interfaceNameParam, procResultParam);

            return (int)procResultParam.Value;
        }

        public async Task<int> InsertBinaryInterfaceAsync(Guid? parentId, string name, string description, byte[] data, int? length, string ext, string interfaceName, CancellationToken cancellationToken = default(CancellationToken))
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@Name", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var dataParam = new SqlParameter { ParameterName = "@Data", SqlDbType = SqlDbType.Image, Direction = ParameterDirection.Input, Value = data, Size = 2147483647 };
            if (dataParam.Value == null)
                dataParam.Value = DBNull.Value;

            var lengthParam = new SqlParameter { ParameterName = "@Length", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = length.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!length.HasValue)
                lengthParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var interfaceNameParam = new SqlParameter { ParameterName = "@InterfaceName", SqlDbType = SqlDbType.VarChar, Direction = ParameterDirection.Input, Value = interfaceName, Size = 100 };
            if (interfaceNameParam.Value == null)
                interfaceNameParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            await Database.ExecuteSqlRawAsync("EXEC @procResult = [dbo].[InsertBinaryInterface] @ParentId, @Name, @Description, @Data, @Length, @Ext, @InterfaceName",  new[] {parentIdParam, nameParam, descriptionParam, dataParam, lengthParam, extParam, interfaceNameParam, procResultParam}, cancellationToken);

            return (int)procResultParam.Value;
        }

        public List<InsertBinaryNodeReturnModel> InsertBinaryNode(Guid? parentId, string name, string description, string ext)
        {
            int procResult;
            return InsertBinaryNode(parentId, name, description, ext, out procResult);
        }

        public List<InsertBinaryNodeReturnModel> InsertBinaryNode(Guid? parentId, string name, string description, string ext, out int procResult)
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@NAME", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[InsertBinaryNode] @ParentId, @NAME, @Description, @ext";
            var procResultData = Set<InsertBinaryNodeReturnModel>()
                .FromSqlRaw(sqlCommand, parentIdParam, nameParam, descriptionParam, extParam, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<InsertBinaryNodeReturnModel>> InsertBinaryNodeAsync(Guid? parentId, string name, string description, string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@NAME", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[InsertBinaryNode] @ParentId, @NAME, @Description, @ext";
            var procResultData = await Set<InsertBinaryNodeReturnModel>()
                .FromSqlRaw(sqlCommand, parentIdParam, nameParam, descriptionParam, extParam)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

        public List<InsertTreeReturnModel> InsertTree(Guid? parentId, string name, string description, string ext)
        {
            int procResult;
            return InsertTree(parentId, name, description, ext, out procResult);
        }

        public List<InsertTreeReturnModel> InsertTree(Guid? parentId, string name, string description, string ext, out int procResult)
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@Name", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[InsertTree] @ParentId, @Name, @Description, @Ext";
            var procResultData = Set<InsertTreeReturnModel>()
                .FromSqlRaw(sqlCommand, parentIdParam, nameParam, descriptionParam, extParam, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<InsertTreeReturnModel>> InsertTreeAsync(Guid? parentId, string name, string description, string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            var parentIdParam = new SqlParameter { ParameterName = "@ParentId", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = parentId.GetValueOrDefault() };
            if (!parentId.HasValue)
                parentIdParam.Value = DBNull.Value;

            var nameParam = new SqlParameter { ParameterName = "@Name", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = name, Size = 50 };
            if (nameParam.Value == null)
                nameParam.Value = DBNull.Value;

            var descriptionParam = new SqlParameter { ParameterName = "@Description", SqlDbType = SqlDbType.NVarChar, Direction = ParameterDirection.Input, Value = description, Size = 300 };
            if (descriptionParam.Value == null)
                descriptionParam.Value = DBNull.Value;

            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.Char, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[InsertTree] @ParentId, @Name, @Description, @Ext";
            var procResultData = await Set<InsertTreeReturnModel>()
                .FromSqlRaw(sqlCommand, parentIdParam, nameParam, descriptionParam, extParam)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

        public List<ProcedureReturnModel> Procedure(int? param1 = null, int? param2 = null)
        {
            int procResult;
            return Procedure(param1, param2, out procResult);
        }

        public List<ProcedureReturnModel> Procedure(int? param1, int? param2, out int procResult)
        {
            var param1Param = new SqlParameter { ParameterName = "@param1", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = param1.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!param1.HasValue)
                param1Param.Value = DBNull.Value;

            var param2Param = new SqlParameter { ParameterName = "@param2", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = param2.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!param2.HasValue)
                param2Param.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[Procedure] @param1, @param2";
            var procResultData = Set<ProcedureReturnModel>()
                .FromSqlRaw(sqlCommand, param1Param, param2Param, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<ProcedureReturnModel>> ProcedureAsync(int? param1 = null, int? param2 = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var param1Param = new SqlParameter { ParameterName = "@param1", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = param1.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!param1.HasValue)
                param1Param.Value = DBNull.Value;

            var param2Param = new SqlParameter { ParameterName = "@param2", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = param2.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!param2.HasValue)
                param2Param.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[Procedure] @param1, @param2";
            var procResultData = await Set<ProcedureReturnModel>()
                .FromSqlRaw(sqlCommand, param1Param, param2Param)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

        public List<SelectBinaryReturnModel> SelectBinary(Guid? id = null)
        {
            int procResult;
            return SelectBinary(id, out procResult);
        }

        public List<SelectBinaryReturnModel> SelectBinary(Guid? id, out int procResult)
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[SelectBinary] @Id";
            var procResultData = Set<SelectBinaryReturnModel>()
                .FromSqlRaw(sqlCommand, idParam, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<SelectBinaryReturnModel>> SelectBinaryAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[SelectBinary] @Id";
            var procResultData = await Set<SelectBinaryReturnModel>()
                .FromSqlRaw(sqlCommand, idParam)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

        public List<SelectBinaryContentsReturnModel> SelectBinaryContents(string ext)
        {
            int procResult;
            return SelectBinaryContents(ext, out procResult);
        }

        public List<SelectBinaryContentsReturnModel> SelectBinaryContents(string ext, out int procResult)
        {
            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.VarChar, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[SelectBinaryContents] @Ext";
            var procResultData = Set<SelectBinaryContentsReturnModel>()
                .FromSqlRaw(sqlCommand, extParam, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<SelectBinaryContentsReturnModel>> SelectBinaryContentsAsync(string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            var extParam = new SqlParameter { ParameterName = "@Ext", SqlDbType = SqlDbType.VarChar, Direction = ParameterDirection.Input, Value = ext, Size = 10 };
            if (extParam.Value == null)
                extParam.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[SelectBinaryContents] @Ext";
            var procResultData = await Set<SelectBinaryContentsReturnModel>()
                .FromSqlRaw(sqlCommand, extParam)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

        public List<SelectBinaryTableReturnModel> SelectBinaryTable()
        {
            int procResult;
            return SelectBinaryTable(out procResult);
        }

        public List<SelectBinaryTableReturnModel> SelectBinaryTable(out int procResult)
        {
            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[SelectBinaryTable]";
            var procResultData = Set<SelectBinaryTableReturnModel>()
                .FromSqlRaw(sqlCommand, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<SelectBinaryTableReturnModel>> SelectBinaryTableAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            const string sqlCommand = "EXEC [dbo].[SelectBinaryTable]";
            var procResultData = await Set<SelectBinaryTableReturnModel>()
                .FromSqlRaw(sqlCommand)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

    }

    #endregion

    #region Database context factory

    public class DataWarehouseFactory : IDesignTimeDbContextFactory<DataWarehouse>
    {
        public DataWarehouse CreateDbContext(string[] args)
        {
            return new DataWarehouse();
        }
    }

    #endregion

    #region Fake Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class FakeDataWarehouse : IDataWarehouse
    {
        public DbSet<BinaryTable> BinaryTables { get; set; } // BinaryTable
        public DbSet<BinaryTree> BinaryTrees { get; set; } // BinaryTree
        public DbSet<ViewBinaryTableId> ViewBinaryTableIds { get; set; } // ViewBinaryTableId
        public DbSet<ViewBinaryTableInfo> ViewBinaryTableInfoes { get; set; } // ViewBinaryTableInfo
        public DbSet<ViewBinaryTreeId> ViewBinaryTreeIds { get; set; } // ViewBinaryTreeId

        public FakeDataWarehouse()
        {
            _database = new FakeDatabaseFacade(new DataWarehouse());

            BinaryTables = new FakeDbSet<BinaryTable>("Id");
            BinaryTrees = new FakeDbSet<BinaryTree>("Id");
            ViewBinaryTableIds = new FakeDbSet<ViewBinaryTableId>();
            ViewBinaryTableInfoes = new FakeDbSet<ViewBinaryTableInfo>();
            ViewBinaryTreeIds = new FakeDbSet<ViewBinaryTreeId>();

        }

        public int SaveChangesCount { get; private set; }
        public virtual int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public virtual int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            return SaveChanges();
        }

        public virtual Task<int> SaveChangesAsync(CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }
        public virtual Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(x => 1, acceptAllChangesOnSuccess, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private DatabaseFacade _database;
        public DatabaseFacade Database { get { return _database; } }

        public DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public override string ToString()
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry Add(object entity)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual Task AddRangeAsync(params object[] entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual async Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new OwnNotImplemented();
        }

        public virtual async ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class
        {
            await Task.CompletedTask;
            throw new OwnNotImplemented();
        }

        public virtual async ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new OwnNotImplemented();
        }

        public virtual void AddRange(IEnumerable<object> entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual void AddRange(params object[] entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry Attach(object entity)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual void AttachRange(IEnumerable<object> entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual void AttachRange(params object[] entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry Entry(object entity)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual TEntity Find<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken)
        {
            throw new OwnNotImplemented();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, params object[] keyValues)
        {
            throw new OwnNotImplemented();
        }

        public virtual object Find(Type entityType, params object[] keyValues)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry Remove(object entity)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual void RemoveRange(IEnumerable<object> entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual void RemoveRange(params object[] entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry Update(object entity)
        {
            throw new OwnNotImplemented();
        }

        public virtual EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class
        {
            throw new OwnNotImplemented();
        }

        public virtual void UpdateRange(IEnumerable<object> entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual void UpdateRange(params object[] entities)
        {
            throw new OwnNotImplemented();
        }

        public virtual IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression)
        {
            throw new OwnNotImplemented();
        }


        // Stored Procedures

        public int DeleteBinary(Guid? id = null)
        {
            return 0;
        }

        public Task<int> DeleteBinaryAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Task.FromResult(0);
        }

        public int DeleteBinaryTree(Guid? id = null)
        {
            return 0;
        }

        public Task<int> DeleteBinaryTreeAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Task.FromResult(0);
        }

        public int InsertBinary(Guid? parentId, string name, string description, byte[] data, string ext)
        {
            return 0;
        }

        public Task<int> InsertBinaryAsync(Guid? parentId, string name, string description, byte[] data, string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Task.FromResult(0);
        }

        public int InsertBinaryInterface(Guid? parentId, string name, string description, byte[] data, int? length, string ext, string interfaceName)
        {
            return 0;
        }

        public Task<int> InsertBinaryInterfaceAsync(Guid? parentId, string name, string description, byte[] data, int? length, string ext, string interfaceName, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Task.FromResult(0);
        }

        public DbSet<InsertBinaryNodeReturnModel> InsertBinaryNodeReturnModel { get; set; }
        public List<InsertBinaryNodeReturnModel> InsertBinaryNode(Guid? parentId, string name, string description, string ext)
        {
            int procResult;
            return InsertBinaryNode(parentId, name, description, ext, out procResult);
        }

        public List<InsertBinaryNodeReturnModel> InsertBinaryNode(Guid? parentId, string name, string description, string ext, out int procResult)
        {
            procResult = 0;
            return new List<InsertBinaryNodeReturnModel>();
        }

        public Task<List<InsertBinaryNodeReturnModel>> InsertBinaryNodeAsync(Guid? parentId, string name, string description, string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(InsertBinaryNode(parentId, name, description, ext, out procResult));
        }

        public DbSet<InsertTreeReturnModel> InsertTreeReturnModel { get; set; }
        public List<InsertTreeReturnModel> InsertTree(Guid? parentId, string name, string description, string ext)
        {
            int procResult;
            return InsertTree(parentId, name, description, ext, out procResult);
        }

        public List<InsertTreeReturnModel> InsertTree(Guid? parentId, string name, string description, string ext, out int procResult)
        {
            procResult = 0;
            return new List<InsertTreeReturnModel>();
        }

        public Task<List<InsertTreeReturnModel>> InsertTreeAsync(Guid? parentId, string name, string description, string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(InsertTree(parentId, name, description, ext, out procResult));
        }

        public DbSet<ProcedureReturnModel> ProcedureReturnModel { get; set; }
        public List<ProcedureReturnModel> Procedure(int? param1 = null, int? param2 = null)
        {
            int procResult;
            return Procedure(param1, param2, out procResult);
        }

        public List<ProcedureReturnModel> Procedure(int? param1, int? param2, out int procResult)
        {
            procResult = 0;
            return new List<ProcedureReturnModel>();
        }

        public Task<List<ProcedureReturnModel>> ProcedureAsync(int? param1 = null, int? param2 = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(Procedure(param1, param2, out procResult));
        }

        public DbSet<SelectBinaryReturnModel> SelectBinaryReturnModel { get; set; }
        public List<SelectBinaryReturnModel> SelectBinary(Guid? id = null)
        {
            int procResult;
            return SelectBinary(id, out procResult);
        }

        public List<SelectBinaryReturnModel> SelectBinary(Guid? id, out int procResult)
        {
            procResult = 0;
            return new List<SelectBinaryReturnModel>();
        }

        public Task<List<SelectBinaryReturnModel>> SelectBinaryAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(SelectBinary(id, out procResult));
        }

        public DbSet<SelectBinaryContentsReturnModel> SelectBinaryContentsReturnModel { get; set; }
        public List<SelectBinaryContentsReturnModel> SelectBinaryContents(string ext)
        {
            int procResult;
            return SelectBinaryContents(ext, out procResult);
        }

        public List<SelectBinaryContentsReturnModel> SelectBinaryContents(string ext, out int procResult)
        {
            procResult = 0;
            return new List<SelectBinaryContentsReturnModel>();
        }

        public Task<List<SelectBinaryContentsReturnModel>> SelectBinaryContentsAsync(string ext, CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(SelectBinaryContents(ext, out procResult));
        }

        public DbSet<SelectBinaryTableReturnModel> SelectBinaryTableReturnModel { get; set; }
        public List<SelectBinaryTableReturnModel> SelectBinaryTable()
        {
            int procResult;
            return SelectBinaryTable(out procResult);
        }

        public List<SelectBinaryTableReturnModel> SelectBinaryTable(out int procResult)
        {
            procResult = 0;
            return new List<SelectBinaryTableReturnModel>();
        }

        public Task<List<SelectBinaryTableReturnModel>> SelectBinaryTableAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(SelectBinaryTable(out procResult));
        }
    }

    #endregion

    #region Fake DbSet

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    public class FakeDbSet<TEntity> :
        DbSet<TEntity>,
        IQueryable<TEntity>,
        IAsyncEnumerable<TEntity>,
        IListSource,
        IResettableService
        where TEntity : class
    {
        private readonly PropertyInfo[] _primaryKeys;
        private ObservableCollection<TEntity> _data;
        private IQueryable _query;
        public override IEntityType EntityType { get; }

        public FakeDbSet()
        {
            _primaryKeys = null;
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override ValueTask<TEntity> FindAsync(object[] keyValues, CancellationToken cancellationToken)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken));
        }

        public override ValueTask<TEntity> FindAsync(params object[] keyValues)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues)));
        }

        public override EntityEntry<TEntity> Add(TEntity entity)
        {
            _data.Add(entity);
            return null;
        }

        public override ValueTask<EntityEntry<TEntity>> AddAsync(TEntity entity, CancellationToken cancellationToken = default)
        {
            return new ValueTask<EntityEntry<TEntity>>(Task<EntityEntry<TEntity>>.Factory.StartNew(() => Add(entity), cancellationToken));
        }

        public override void AddRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override void AddRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override Task AddRangeAsync(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities));
        }

        public override Task AddRangeAsync(IEnumerable<TEntity> entities, CancellationToken cancellationToken = default)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities), cancellationToken);
        }

        public override EntityEntry<TEntity> Attach(TEntity entity)
        {
            if (entity == null) throw new ArgumentNullException("entity");
            return Add(entity);
        }

        public override void AttachRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override void AttachRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override EntityEntry<TEntity> Remove(TEntity entity)
        {
            _data.Remove(entity);
            return null;
        }

        public override void RemoveRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities.ToList())
                _data.Remove(entity);
        }

        public override void RemoveRange(IEnumerable<TEntity> entities)
        {
            RemoveRange(entities.ToArray());
        }

        public override EntityEntry<TEntity> Update(TEntity entity)
        {
            _data.Remove(entity);
            _data.Add(entity);
            return null;
        }

        public override void UpdateRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            RemoveRange(entities);
            AddRange(entities);
        }

        public override void UpdateRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            var array = entities.ToArray();        RemoveRange(array);
            AddRange(array);
        }

        bool IListSource.ContainsListCollection => true;

        public IList GetList()
        {
            return _data;
        }

        IList IListSource.GetList()
        {
            return _data;
        }

        Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_data); }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        IEnumerator<TEntity> IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        public override IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }

        public void ResetState()
        {
            _data  = new ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public Task ResetStateAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.Factory.StartNew(() => ResetState());
        }
    }

    public class FakeDbAsyncQueryProvider<TEntity> : FakeQueryProvider<TEntity>, IAsyncEnumerable<TEntity>, IAsyncQueryProvider
    {
        public FakeDbAsyncQueryProvider(Expression expression) : base(expression)
        {
        }

        public FakeDbAsyncQueryProvider(IEnumerable<TEntity> enumerable) : base(enumerable)
        {
        }

        public TResult ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
        {
            var expectedResultType = typeof(TResult).GetGenericArguments()[0];
            var executionResult = typeof(IQueryProvider)
                .GetMethods()
                .First(method => method.Name == nameof(IQueryProvider.Execute) && method.IsGenericMethod)
                .MakeGenericMethod(expectedResultType)
                .Invoke(this, new object[] { expression });

            return (TResult) typeof(Task).GetMethod(nameof(Task.FromResult))
                ?.MakeGenericMethod(expectedResultType)
                .Invoke(null, new[] { executionResult });
        }

        public IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }
    }

    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, IAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(IEnumerable<T> enumerable)
            : base(enumerable)
        {
        }

        public FakeDbAsyncEnumerable(Expression expression)
            : base(expression)
        {
        }

        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = new CancellationToken())
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        IAsyncEnumerator<T> IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
        {
            return GetAsyncEnumerator(cancellationToken);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.AsEnumerable().GetEnumerator();
        }
    }

    public class FakeDbAsyncEnumerator<T> : IAsyncEnumerator<T>
    {
        private readonly IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        public ValueTask<bool> MoveNextAsync()
        {
            return new ValueTask<bool>(_inner.MoveNext());
        }

        public ValueTask DisposeAsync()
        {
            _inner.Dispose();
            return new ValueTask(Task.CompletedTask);
        }
    }

    public abstract class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider
    {
        private IEnumerable<T> _enumerable;

        protected FakeQueryProvider(Expression expression)
        {
            Expression = expression;
        }

        protected FakeQueryProvider(IEnumerable<T> enumerable)
        {
            _enumerable = enumerable;
            Expression = enumerable.AsQueryable().Expression;
        }

        public IQueryable CreateQuery(Expression expression)
        {
            if (expression is MethodCallExpression m)
            {
                var resultType = m.Method.ReturnType; // it should be IQueryable<T>
                var tElement = resultType.GetGenericArguments().First();
                return (IQueryable) CreateInstance(tElement, expression);
            }

            return CreateQuery<T>(expression);
        }

        public IQueryable<TEntity> CreateQuery<TEntity>(Expression expression)
        {
            return (IQueryable<TEntity>) CreateInstance(typeof(TEntity), expression);
        }

        private object CreateInstance(Type tElement, Expression expression)
        {
            var queryType = GetType().GetGenericTypeDefinition().MakeGenericType(tElement);
            return Activator.CreateInstance(queryType, expression);
        }

        public object Execute(Expression expression)
        {
            return CompileExpressionItem<object>(expression);
        }

        public TResult Execute<TResult>(Expression expression)
        {
            return CompileExpressionItem<TResult>(expression);
        }

        IEnumerator<T> IEnumerable<T>.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        public Type ElementType => typeof(T);

        public Expression Expression { get; }

        public IQueryProvider Provider => this;

        private static TResult CompileExpressionItem<TResult>(Expression expression)
        {
            var visitor = new FakeExpressionVisitor();
            var body = visitor.Visit(expression);
            var f = Expression.Lambda<Func<TResult>>(body ?? throw new InvalidOperationException(string.Format("{0} is null", nameof(body))), (IEnumerable<ParameterExpression>) null);
            return f.Compile()();
        }
    }

    public class FakeExpressionVisitor : ExpressionVisitor
    {
    }

    public class FakeDatabaseFacade : DatabaseFacade
    {
        public FakeDatabaseFacade(DbContext context) : base(context)
        {
        }

        public override bool EnsureCreated()
        {
            return true;
        }

        public override Task<bool> EnsureCreatedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureCreated());
        }

        public override bool EnsureDeleted()
        {
            return true;
        }

        public override Task<bool> EnsureDeletedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureDeleted());
        }

        public override bool CanConnect()
        {
            return true;
        }

        public override Task<bool> CanConnectAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(CanConnect());
        }

        public override IDbContextTransaction BeginTransaction()
        {
            return new FakeDbContextTransaction();
        }

        public override Task<IDbContextTransaction> BeginTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(BeginTransaction());
        }

        public override void CommitTransaction()
        {
        }

        public override Task CommitTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override void RollbackTransaction()
        {
        }

        public override Task RollbackTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override IExecutionStrategy CreateExecutionStrategy()
        {
            return null;
        }

        public override string ToString()
        {
            return string.Empty;
        }
    }

    public class FakeDbContextTransaction : IDbContextTransaction
    {
        public Guid TransactionId => Guid.NewGuid();
        public void Commit() { }
        public void Rollback() { }
        public Task CommitAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public Task RollbackAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public void Dispose() { }
        public ValueTask DisposeAsync() => default;
    }

    #endregion

    #region POCO classes

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // BinaryTable
    public class BinaryTable
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid ParentId { get; set; } // ParentId
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 300)
        public byte[] Data { get; set; } // Data (length: 2147483647)
        public string Length { get; set; } // Length (length: 30)
        public string Ext { get; set; } // Ext (length: 10)

        // Foreign keys

        /// <summary>
        /// Parent BinaryTree pointed by [BinaryTable].([ParentId]) (FK_BinaryTable_BinaryTree)
        /// </summary>
        public BinaryTree BinaryTree { get; set; } // FK_BinaryTable_BinaryTree

        public BinaryTable()
        {
            Id = Guid.NewGuid();
        }
    }

    // BinaryTree
    public class BinaryTree
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid ParentId { get; set; } // ParentId
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 300)
        public string Ext { get; set; } // ext (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child BinaryTables where [BinaryTable].[ParentId] point to this entity (FK_BinaryTable_BinaryTree)
        /// </summary>
        public ICollection<BinaryTable> BinaryTables { get; set; } // BinaryTable.FK_BinaryTable_BinaryTree

        /// <summary>
        /// Child BinaryTrees where [BinaryTree].[ParentId] point to this entity (FK_BinaryTree_BinaryTree)
        /// </summary>
        public ICollection<BinaryTree> BinaryTrees { get; set; } // BinaryTree.FK_BinaryTree_BinaryTree

        // Foreign keys

        /// <summary>
        /// Parent BinaryTree pointed by [BinaryTree].([ParentId]) (FK_BinaryTree_BinaryTree)
        /// </summary>
        public BinaryTree Parent { get; set; } // FK_BinaryTree_BinaryTree

        public BinaryTree()
        {
            Id = Guid.NewGuid();
            BinaryTables = new List<BinaryTable>();
            BinaryTrees = new List<BinaryTree>();
        }
    }

    // ViewBinaryTableId
    public class ViewBinaryTableId
    {
        public Guid Id { get; set; } // Id
    }

    // ViewBinaryTableInfo
    public class ViewBinaryTableInfo
    {
        public Guid Id { get; set; } // Id
        public Guid ParentId { get; set; } // ParentId
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 300)
        public string Ext { get; set; } // Ext (length: 10)
    }

    // ViewBinaryTreeId
    public class ViewBinaryTreeId
    {
        public Guid Id { get; set; } // Id
        public Guid ParentId { get; set; } // ParentId
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 300)
        public string Ext { get; set; } // Ext (length: 10)
    }


    #endregion

    #region POCO Configuration

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // BinaryTable
    public class BinaryTableConfiguration : IEntityTypeConfiguration<BinaryTable>
    {
        public void Configure(EntityTypeBuilder<BinaryTable> builder)
        {
            builder.ToTable("BinaryTable", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_BinaryTable").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(300)").IsRequired().HasMaxLength(300);
            builder.Property(x => x.Data).HasColumnName(@"Data").HasColumnType("image(2147483647)").IsRequired().HasMaxLength(2147483647);
            builder.Property(x => x.Length).HasColumnName(@"Length").HasColumnType("nvarchar(30)").IsRequired().HasMaxLength(30);
            builder.Property(x => x.Ext).HasColumnName(@"Ext").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);

            // Foreign keys
            builder.HasOne(a => a.BinaryTree).WithMany(b => b.BinaryTables).HasForeignKey(c => c.ParentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_BinaryTable_BinaryTree");
        }
    }

    // BinaryTree
    public class BinaryTreeConfiguration : IEntityTypeConfiguration<BinaryTree>
    {
        public void Configure(EntityTypeBuilder<BinaryTree> builder)
        {
            builder.ToTable("BinaryTree", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_BinaryTree").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(300)").IsRequired().HasMaxLength(300);
            builder.Property(x => x.Ext).HasColumnName(@"ext").HasColumnType("char(10)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(10);

            // Foreign keys
            builder.HasOne(a => a.Parent).WithMany(b => b.BinaryTrees).HasForeignKey(c => c.ParentId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_BinaryTree_BinaryTree");
        }
    }

    // ViewBinaryTableId
    public class ViewBinaryTableIdConfiguration : IEntityTypeConfiguration<ViewBinaryTableId>
    {
        public void Configure(EntityTypeBuilder<ViewBinaryTableId> builder)
        {
            builder.ToView("ViewBinaryTableId", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
        }
    }

    // ViewBinaryTableInfo
    public class ViewBinaryTableInfoConfiguration : IEntityTypeConfiguration<ViewBinaryTableInfo>
    {
        public void Configure(EntityTypeBuilder<ViewBinaryTableInfo> builder)
        {
            builder.ToView("ViewBinaryTableInfo", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(300)").IsRequired().HasMaxLength(300);
            builder.Property(x => x.Ext).HasColumnName(@"Ext").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
        }
    }

    // ViewBinaryTreeId
    public class ViewBinaryTreeIdConfiguration : IEntityTypeConfiguration<ViewBinaryTreeId>
    {
        public void Configure(EntityTypeBuilder<ViewBinaryTreeId> builder)
        {
            builder.ToView("ViewBinaryTreeId", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(300)").IsRequired().HasMaxLength(300);
            builder.Property(x => x.Ext).HasColumnName(@"Ext").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
        }
    }


    #endregion

    #region Stored procedure return models

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class InsertBinaryNodeReturnModel
    {
        public Guid Id { get; set; }
    }

    public class InsertTreeReturnModel
    {
        public Guid Id { get; set; }
    }

    public class ProcedureReturnModel
    {
        public int? Column1 { get; set; }
        public int? Column2 { get; set; }
    }

    public class SelectBinaryContentsReturnModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Length { get; set; }
    }

    public class SelectBinaryReturnModel
    {
        public byte[] Data { get; set; }
        public string Ext { get; set; }
    }

    public class SelectBinaryTableReturnModel
    {
        public Guid Id { get; set; }
        public Guid ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Ext { get; set; }
    }


    #endregion

}
// </auto-generated>
