// Licence file C:\Users\monst\OneDrive\Documents\ReversePOCO.txt not found.
// Please obtain your licence file at www.ReversePOCO.co.uk, and place it in your documents folder shown above.
// Defaulting to Trial version.
// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace Trading.Database.SqlServer
{
    #region Database context interface

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public interface ITradingHistory : IDisposable
    {
        DbSet<DataHistory> DataHistories { get; set; } // DataHistories
        DbSet<HistoryMessage> HistoryMessages { get; set; } // HistoryMessages

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity Find<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken);
        ValueTask<object> FindAsync(Type entityType, params object[] keyValues);
        object Find(Type entityType, params object[] keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);

        // Stored Procedures
        int DeleteHistoryBySymbolId(Guid? id);
        Task<int> DeleteHistoryBySymbolIdAsync(Guid? id, CancellationToken cancellationToken = default(CancellationToken));

        List<SelectHistoryByDateReturnModel> SelectHistoryByDate(Guid? id, DateTime? begin, DateTime? end);
        List<SelectHistoryByDateReturnModel> SelectHistoryByDate(Guid? id, DateTime? begin, DateTime? end, out int procResult);
        Task<List<SelectHistoryByDateReturnModel>> SelectHistoryByDateAsync(Guid? id, DateTime? begin, DateTime? end, CancellationToken cancellationToken = default(CancellationToken));

        List<SelectSymbolsReturnModel> SelectSymbols();
        List<SelectSymbolsReturnModel> SelectSymbols(out int procResult);
        Task<List<SelectSymbolsReturnModel>> SelectSymbolsAsync(CancellationToken cancellationToken = default(CancellationToken));

    }

    #endregion

    #region Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class TradingHistory : DbContext, ITradingHistory
    {
        public TradingHistory()
        {
        }

        public TradingHistory(DbContextOptions<TradingHistory> options)
            : base(options)
        {
        }

        public DbSet<DataHistory> DataHistories { get; set; } // DataHistories
        public DbSet<HistoryMessage> HistoryMessages { get; set; } // HistoryMessages

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=IVANKOV\SQLEXPRESS;Initial Catalog=TradeStation;Integrated Security=True;Encrypt=False;MultipleActiveResultSets=True;TrustServerCertificate=true");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new DataHistoryConfiguration());
            modelBuilder.ApplyConfiguration(new HistoryMessageConfiguration());

            modelBuilder.Entity<SelectHistoryByDateReturnModel>().HasNoKey();
            modelBuilder.Entity<SelectSymbolsReturnModel>().HasNoKey();
        }


        // Stored Procedures
        public int DeleteHistoryBySymbolId(Guid? id = null)
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[DeleteHistoryBySymbolId] @Id", idParam, procResultParam);

            return (int)procResultParam.Value;
        }

        public async Task<int> DeleteHistoryBySymbolIdAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            await Database.ExecuteSqlRawAsync("EXEC @procResult = [dbo].[DeleteHistoryBySymbolId] @Id",  new[] {idParam, procResultParam}, cancellationToken);

            return (int)procResultParam.Value;
        }

        public List<SelectHistoryByDateReturnModel> SelectHistoryByDate(Guid? id = null, DateTime? begin = null, DateTime? end = null)
        {
            int procResult;
            return SelectHistoryByDate(id, begin, end, out procResult);
        }

        public List<SelectHistoryByDateReturnModel> SelectHistoryByDate(Guid? id, DateTime? begin, DateTime? end, out int procResult)
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var beginParam = new SqlParameter { ParameterName = "@BEGIN", SqlDbType = SqlDbType.DateTime, Direction = ParameterDirection.Input, Value = begin.GetValueOrDefault() };
            if (!begin.HasValue)
                beginParam.Value = DBNull.Value;

            var endParam = new SqlParameter { ParameterName = "@END", SqlDbType = SqlDbType.DateTime, Direction = ParameterDirection.Input, Value = end.GetValueOrDefault() };
            if (!end.HasValue)
                endParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[SelectHistoryByDate] @Id, @BEGIN, @END";
            var procResultData = Set<SelectHistoryByDateReturnModel>()
                .FromSqlRaw(sqlCommand, idParam, beginParam, endParam, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<SelectHistoryByDateReturnModel>> SelectHistoryByDateAsync(Guid? id = null, DateTime? begin = null, DateTime? end = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var idParam = new SqlParameter { ParameterName = "@Id", SqlDbType = SqlDbType.UniqueIdentifier, Direction = ParameterDirection.Input, Value = id.GetValueOrDefault() };
            if (!id.HasValue)
                idParam.Value = DBNull.Value;

            var beginParam = new SqlParameter { ParameterName = "@BEGIN", SqlDbType = SqlDbType.DateTime, Direction = ParameterDirection.Input, Value = begin.GetValueOrDefault() };
            if (!begin.HasValue)
                beginParam.Value = DBNull.Value;

            var endParam = new SqlParameter { ParameterName = "@END", SqlDbType = SqlDbType.DateTime, Direction = ParameterDirection.Input, Value = end.GetValueOrDefault() };
            if (!end.HasValue)
                endParam.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[SelectHistoryByDate] @Id, @BEGIN, @END";
            var procResultData = await Set<SelectHistoryByDateReturnModel>()
                .FromSqlRaw(sqlCommand, idParam, beginParam, endParam)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

        public List<SelectSymbolsReturnModel> SelectSymbols()
        {
            int procResult;
            return SelectSymbols(out procResult);
        }

        public List<SelectSymbolsReturnModel> SelectSymbols(out int procResult)
        {
            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[SelectSymbols]";
            var procResultData = Set<SelectSymbolsReturnModel>()
                .FromSqlRaw(sqlCommand, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<SelectSymbolsReturnModel>> SelectSymbolsAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            const string sqlCommand = "EXEC [dbo].[SelectSymbols]";
            var procResultData = await Set<SelectSymbolsReturnModel>()
                .FromSqlRaw(sqlCommand)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

    }

    #endregion

    #region Database context factory

    public class TradingHistoryFactory : IDesignTimeDbContextFactory<TradingHistory>
    {
        public TradingHistory CreateDbContext(string[] args)
        {
            return new TradingHistory();
        }
    }

    #endregion

    #region Fake Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class FakeTradingHistory : ITradingHistory
    {
        public DbSet<DataHistory> DataHistories { get; set; } // DataHistories
        public DbSet<HistoryMessage> HistoryMessages { get; set; } // HistoryMessages

        public FakeTradingHistory()
        {
            _database = new FakeDatabaseFacade(new TradingHistory());

            DataHistories = new FakeDbSet<DataHistory>("Id");
            HistoryMessages = new FakeDbSet<HistoryMessage>("Id");

        }

        public int SaveChangesCount { get; private set; }
        public virtual int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public virtual int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            return SaveChanges();
        }

        public virtual Task<int> SaveChangesAsync(CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }
        public virtual Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(x => 1, acceptAllChangesOnSuccess, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private DatabaseFacade _database;
        public DatabaseFacade Database { get { return _database; } }

        public DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new NotImplementedException();
        }

        public override string ToString()
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Add(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual Task AddRangeAsync(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual async Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual async ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual async ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual void AddRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void AddRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Attach(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void AttachRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void AttachRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Entry(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual TEntity Find<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, params object[] keyValues)
        {
            throw new NotImplementedException();
        }

        public virtual object Find(Type entityType, params object[] keyValues)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Remove(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void RemoveRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void RemoveRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Update(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void UpdateRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void UpdateRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression)
        {
            throw new NotImplementedException();
        }


        // Stored Procedures

        public int DeleteHistoryBySymbolId(Guid? id = null)
        {
            return 0;
        }

        public Task<int> DeleteHistoryBySymbolIdAsync(Guid? id = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Task.FromResult(0);
        }

        public DbSet<SelectHistoryByDateReturnModel> SelectHistoryByDateReturnModel { get; set; }
        public List<SelectHistoryByDateReturnModel> SelectHistoryByDate(Guid? id = null, DateTime? begin = null, DateTime? end = null)
        {
            int procResult;
            return SelectHistoryByDate(id, begin, end, out procResult);
        }

        public List<SelectHistoryByDateReturnModel> SelectHistoryByDate(Guid? id, DateTime? begin, DateTime? end, out int procResult)
        {
            procResult = 0;
            return new List<SelectHistoryByDateReturnModel>();
        }

        public Task<List<SelectHistoryByDateReturnModel>> SelectHistoryByDateAsync(Guid? id = null, DateTime? begin = null, DateTime? end = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(SelectHistoryByDate(id, begin, end, out procResult));
        }

        public DbSet<SelectSymbolsReturnModel> SelectSymbolsReturnModel { get; set; }
        public List<SelectSymbolsReturnModel> SelectSymbols()
        {
            int procResult;
            return SelectSymbols(out procResult);
        }

        public List<SelectSymbolsReturnModel> SelectSymbols(out int procResult)
        {
            procResult = 0;
            return new List<SelectSymbolsReturnModel>();
        }

        public Task<List<SelectSymbolsReturnModel>> SelectSymbolsAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            int procResult;
            return Task.FromResult(SelectSymbols(out procResult));
        }
    }

    #endregion

    #region Fake DbSet

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    public class FakeDbSet<TEntity> :
        DbSet<TEntity>,
        IQueryable<TEntity>,
        IAsyncEnumerable<TEntity>,
        IListSource,
        IResettableService
        where TEntity : class
    {
        private readonly PropertyInfo[] _primaryKeys;
        private ObservableCollection<TEntity> _data;
        private IQueryable _query;
        public override IEntityType EntityType { get; }

        public FakeDbSet()
        {
            _primaryKeys = null;
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override ValueTask<TEntity> FindAsync(object[] keyValues, CancellationToken cancellationToken)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken));
        }

        public override ValueTask<TEntity> FindAsync(params object[] keyValues)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues)));
        }

        public override EntityEntry<TEntity> Add(TEntity entity)
        {
            _data.Add(entity);
            return null;
        }

        public override ValueTask<EntityEntry<TEntity>> AddAsync(TEntity entity, CancellationToken cancellationToken = default)
        {
            return new ValueTask<EntityEntry<TEntity>>(Task<EntityEntry<TEntity>>.Factory.StartNew(() => Add(entity), cancellationToken));
        }

        public override void AddRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override void AddRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override Task AddRangeAsync(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities));
        }

        public override Task AddRangeAsync(IEnumerable<TEntity> entities, CancellationToken cancellationToken = default)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities), cancellationToken);
        }

        public override EntityEntry<TEntity> Attach(TEntity entity)
        {
            if (entity == null) throw new ArgumentNullException("entity");
            return Add(entity);
        }

        public override void AttachRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override void AttachRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override EntityEntry<TEntity> Remove(TEntity entity)
        {
            _data.Remove(entity);
            return null;
        }

        public override void RemoveRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities.ToList())
                _data.Remove(entity);
        }

        public override void RemoveRange(IEnumerable<TEntity> entities)
        {
            RemoveRange(entities.ToArray());
        }

        public override EntityEntry<TEntity> Update(TEntity entity)
        {
            _data.Remove(entity);
            _data.Add(entity);
            return null;
        }

        public override void UpdateRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            RemoveRange(entities);
            AddRange(entities);
        }

        public override void UpdateRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            var array = entities.ToArray();        RemoveRange(array);
            AddRange(array);
        }

        bool IListSource.ContainsListCollection => true;

        public IList GetList()
        {
            return _data;
        }

        IList IListSource.GetList()
        {
            return _data;
        }

        Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_data); }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        IEnumerator<TEntity> IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        public override IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }

        public void ResetState()
        {
            _data  = new ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public Task ResetStateAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.Factory.StartNew(() => ResetState());
        }
    }

    public class FakeDbAsyncQueryProvider<TEntity> : FakeQueryProvider<TEntity>, IAsyncEnumerable<TEntity>, IAsyncQueryProvider
    {
        public FakeDbAsyncQueryProvider(Expression expression) : base(expression)
        {
        }

        public FakeDbAsyncQueryProvider(IEnumerable<TEntity> enumerable) : base(enumerable)
        {
        }

        public TResult ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
        {
            var expectedResultType = typeof(TResult).GetGenericArguments()[0];
            var executionResult = typeof(IQueryProvider)
                .GetMethods()
                .First(method => method.Name == nameof(IQueryProvider.Execute) && method.IsGenericMethod)
                .MakeGenericMethod(expectedResultType)
                .Invoke(this, new object[] { expression });

            return (TResult) typeof(Task).GetMethod(nameof(Task.FromResult))
                ?.MakeGenericMethod(expectedResultType)
                .Invoke(null, new[] { executionResult });
        }

        public IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }
    }

    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, IAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(IEnumerable<T> enumerable)
            : base(enumerable)
        {
        }

        public FakeDbAsyncEnumerable(Expression expression)
            : base(expression)
        {
        }

        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = new CancellationToken())
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        IAsyncEnumerator<T> IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
        {
            return GetAsyncEnumerator(cancellationToken);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.AsEnumerable().GetEnumerator();
        }
    }

    public class FakeDbAsyncEnumerator<T> : IAsyncEnumerator<T>
    {
        private readonly IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        public ValueTask<bool> MoveNextAsync()
        {
            return new ValueTask<bool>(_inner.MoveNext());
        }

        public ValueTask DisposeAsync()
        {
            _inner.Dispose();
            return new ValueTask(Task.CompletedTask);
        }
    }

    public abstract class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider
    {
        private IEnumerable<T> _enumerable;

        protected FakeQueryProvider(Expression expression)
        {
            Expression = expression;
        }

        protected FakeQueryProvider(IEnumerable<T> enumerable)
        {
            _enumerable = enumerable;
            Expression = enumerable.AsQueryable().Expression;
        }

        public IQueryable CreateQuery(Expression expression)
        {
            if (expression is MethodCallExpression m)
            {
                var resultType = m.Method.ReturnType; // it should be IQueryable<T>
                var tElement = resultType.GetGenericArguments().First();
                return (IQueryable) CreateInstance(tElement, expression);
            }

            return CreateQuery<T>(expression);
        }

        public IQueryable<TEntity> CreateQuery<TEntity>(Expression expression)
        {
            return (IQueryable<TEntity>) CreateInstance(typeof(TEntity), expression);
        }

        private object CreateInstance(Type tElement, Expression expression)
        {
            var queryType = GetType().GetGenericTypeDefinition().MakeGenericType(tElement);
            return Activator.CreateInstance(queryType, expression);
        }

        public object Execute(Expression expression)
        {
            return CompileExpressionItem<object>(expression);
        }

        public TResult Execute<TResult>(Expression expression)
        {
            return CompileExpressionItem<TResult>(expression);
        }

        IEnumerator<T> IEnumerable<T>.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        public Type ElementType => typeof(T);

        public Expression Expression { get; }

        public IQueryProvider Provider => this;

        private static TResult CompileExpressionItem<TResult>(Expression expression)
        {
            var visitor = new FakeExpressionVisitor();
            var body = visitor.Visit(expression);
            var f = Expression.Lambda<Func<TResult>>(body ?? throw new InvalidOperationException(string.Format("{0} is null", nameof(body))), (IEnumerable<ParameterExpression>) null);
            return f.Compile()();
        }
    }

    public class FakeExpressionVisitor : ExpressionVisitor
    {
    }

    public class FakeDatabaseFacade : DatabaseFacade
    {
        public FakeDatabaseFacade(DbContext context) : base(context)
        {
        }

        public override bool EnsureCreated()
        {
            return true;
        }

        public override Task<bool> EnsureCreatedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureCreated());
        }

        public override bool EnsureDeleted()
        {
            return true;
        }

        public override Task<bool> EnsureDeletedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureDeleted());
        }

        public override bool CanConnect()
        {
            return true;
        }

        public override Task<bool> CanConnectAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(CanConnect());
        }

        public override IDbContextTransaction BeginTransaction()
        {
            return new FakeDbContextTransaction();
        }

        public override Task<IDbContextTransaction> BeginTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(BeginTransaction());
        }

        public override void CommitTransaction()
        {
        }

        public override Task CommitTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override void RollbackTransaction()
        {
        }

        public override Task RollbackTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override IExecutionStrategy CreateExecutionStrategy()
        {
            return null;
        }

        public override string ToString()
        {
            return string.Empty;
        }
    }

    public class FakeDbContextTransaction : IDbContextTransaction
    {
        public Guid TransactionId => Guid.NewGuid();
        public void Commit() { }
        public void Rollback() { }
        public Task CommitAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public Task RollbackAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public void Dispose() { }
        public ValueTask DisposeAsync() => default;
    }

    #endregion

    #region POCO classes

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // DataHistories
    public class DataHistory
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) DataHistory pointed by [DataHistories].[Id] (FK_DataHistories_DataHistories)
        /// </summary>
        public DataHistory DataHistory2 { get; set; } // DataHistories.FK_DataHistories_DataHistories

        /// <summary>
        /// Child HistoryMessages where [HistoryMessages].[historyId] point to this entity (FK_HistoryMessages_DataHistories)
        /// </summary>
        public ICollection<HistoryMessage> HistoryMessages { get; set; } // HistoryMessages.FK_HistoryMessages_DataHistories

        // Foreign keys

        /// <summary>
        /// Parent DataHistory pointed by [DataHistories].([Id]) (FK_DataHistories_DataHistories)
        /// </summary>
        public DataHistory DataHistory1 { get; set; } // FK_DataHistories_DataHistories

        public DataHistory()
        {
            HistoryMessages = new List<HistoryMessage>();
        }
    }

    // HistoryMessages
    public class HistoryMessage
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid HistoryId { get; set; } // historyId
        public int Number { get; set; } // number
        public int RequestId { get; set; } // RequestId
        public DateTime Date { get; set; } // Date
        public double OpenF { get; set; } // OpenF
        public double High { get; set; } // High
        public double Low { get; set; } // Low
        public double CloseF { get; set; } // CloseF
        public decimal Volume { get; set; } // Volume
        public int Count { get; set; } // Count
        public decimal Wap { get; set; } // Wap
        public bool HasGaps { get; set; } // HasGaps

        // Foreign keys

        /// <summary>
        /// Parent DataHistory pointed by [HistoryMessages].([HistoryId]) (FK_HistoryMessages_DataHistories)
        /// </summary>
        public DataHistory DataHistory { get; set; } // FK_HistoryMessages_DataHistories

        public HistoryMessage()
        {
            Id = Guid.NewGuid();
        }
    }


    #endregion

    #region POCO Configuration

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // DataHistories
    public class DataHistoryConfiguration : IEntityTypeConfiguration<DataHistory>
    {
        public void Configure(EntityTypeBuilder<DataHistory> builder)
        {
            builder.ToTable("DataHistories", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_DataHistories").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.DataHistory1).WithOne(b => b.DataHistory2).HasForeignKey<DataHistory>(c => c.Id).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_DataHistories_DataHistories");
        }
    }

    // HistoryMessages
    public class HistoryMessageConfiguration : IEntityTypeConfiguration<HistoryMessage>
    {
        public void Configure(EntityTypeBuilder<HistoryMessage> builder)
        {
            builder.ToTable("HistoryMessages", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_HistoryMessages").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.HistoryId).HasColumnName(@"historyId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Number).HasColumnName(@"number").HasColumnType("int").IsRequired();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.OpenF).HasColumnName(@"OpenF").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.High).HasColumnName(@"High").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.Low).HasColumnName(@"Low").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.CloseF).HasColumnName(@"CloseF").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.Volume).HasColumnName(@"Volume").HasColumnType("decimal(18,0)").HasPrecision(18,0).IsRequired();
            builder.Property(x => x.Count).HasColumnName(@"Count").HasColumnType("int").IsRequired();
            builder.Property(x => x.Wap).HasColumnName(@"Wap").HasColumnType("decimal(18,0)").HasPrecision(18,0).IsRequired();
            builder.Property(x => x.HasGaps).HasColumnName(@"HasGaps").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.DataHistory).WithMany(b => b.HistoryMessages).HasForeignKey(c => c.HistoryId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_HistoryMessages_DataHistories");
        }
    }


    #endregion

    #region Stored procedure return models

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class SelectHistoryByDateReturnModel
    {
        public Guid Id { get; set; }
        public Guid historyId { get; set; }
        public int number { get; set; }
        public int RequestId { get; set; }
        public DateTime Date { get; set; }
        public double OpenF { get; set; }
        public double High { get; set; }
        public double Low { get; set; }
        public double CloseF { get; set; }
        public decimal Volume { get; set; }
        public int Count { get; set; }
        public decimal Wap { get; set; }
        public bool HasGaps { get; set; }
    }

    public class SelectSymbolsReturnModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }


    #endregion

}
// </auto-generated>
