<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\runtimes\dotnet\DynamicLinkLibraries\AssemblyService\AssemblyService.csproj" />
    <ProjectReference Include="..\..\..\..\DynamicLinkLibraries\Diagram\Diagram.TypeScript\Diagram.TypeScript.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\runtimes\dotnet\DynamicLinkLibraries\Diagram\Diagram\Diagram.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\runtimes\dotnet\ExternalLibraries\Atmosphere\DinAtm\DinAtm.Portable\DinAtm.Portable.csproj" />
  </ItemGroup>

</Project>
