//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP_Simulator.Light {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class SettingsTrading : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsTrading defaultInstance = ((SettingsTrading)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsTrading())));
        
        public static SettingsTrading Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TradingDataConnectionString {
            get {
                return ((string)(this["TradingDataConnectionString"]));
            }
            set {
                this["TradingDataConnectionString"] = value;
            }
        }
    }
}
